### PR TITLE
drop support for django 1.x

### PR DESCRIPTION
**Pull request by sheppard**
See discussion in #30.

### CODE REVIEW

**Review by atb00ker — COMMENTED** [review]
Great! 
I think the [`setup.py` also needs to be updated](https://github.com/openwisp/django-swappable-models/blob/master/setup.py#L36-L54).

**Comment by sheppard** [comment]
I updated the classifiers.

**Review by atb00ker — APPROVED** [review]
> I updated the classifiers.

Great, I think it should be ready then. (I'd defer to another review though. (May take a while)

**Review by nemesisdesign — APPROVED** [review]
Let's go! Thank you @sheppard

**Pull request merged**
