### PR TITLE
[ci] Dropped python 3.5

### PR DESCRIPTION
**Pull request by nemesisdesign**

### CODE REVIEW

**Comment by nemesisdesign** [comment]
This looks more maintainable on our side.

**Review by devkapilbansal — DISMISSED** [review]

**Comment by sheppard** [comment]
Looks good overall.  Did you want to add Python 3.9 as well or do that later?  Also be sure to update the classifiers in setup.py (which will update the badge once released).

For this library in particular, I previously had an informal policy of preserving support for deprecated Python/Django versions as long as they didn't require significant effort.  That said, it certainly makes sense to follow the standard practice of dropping support once the versions are EOL.

With that in mind, it would be good to remove the doubly nested try/catch in load_model, as well as the (undocumented) South `orm` argument.  So the whole function would just be this:

```python
from django.apps import apps

# ...

def load_model(app_label, model, required=True, require_ready=True):
    """
    Load the specified model class, or the class it was swapped out for.
    """
    swapped = is_swapped(app_label, model)
    if swapped:
        app_label, model = split(swapped)

    try:
        cls = apps.get_model(app_label, model, require_ready=require_ready)
    except LookupError:
        cls = None

    if cls is None and required:
        raise ImproperlyConfigured(
            "Could not find {name}!".format(name=join(app_label, model))
        )
    return cls
```

It's probably fine to just do this and bump the major version - the only functional change since 1.1.2 is #22, and users who need that will already be on Django 2 or newer.

**Review by sheppard — DISMISSED** [review]

**Comment by nemesisdesign** [comment]
@sheppard I can add python 3.9 here, can you link the pieces of code that would have to be removed please?

EG:

https://github.com/openwisp/django-swappable-models/blob/81d383dab242b9414cde8d5cb304cdc9e25a1914/swapper/__init__.py#L69-L70

What else? Is the `orm` parameter specific for South?

**Comment by sheppard** [comment]
Yes, `orm` was for south .  I opened #31 which can be merged after this PR.

**Review by nemesisdesign — COMMENTED** [review]
@sheppard I added python 3.9 for django 3.1, could you please double check?

**Review by sheppard — APPROVED** [review]

**Pull request merged**
